name: macare_agent
version: 1.0.0+1
publish_to: none
description: MACare Agent App
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  google_fonts: ^6.1.0
  dio: ^5.4.0
  url_launcher: ^6.0.10
  flutter_phone_direct_caller: ^2.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter


flutter: 
  uses-material-design: true

  assets:
  - assets/images/