name: macare_agent
version: 1.0.0+1
publish_to: none
description: MACare Agent App
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  get_storage: ^2.1.1
  firebase_analytics: ^10.7.4
  firebase_messaging:
  flutter_local_notifications:
  firebase_core:
  intl:
  fluttertoast: ^8.0.8
  custom_alert_dialog_box: ^1.0.2
  flutter_check_box_rounded: ^3.2.3
  cupertino_icons: ^1.0.2
  get: 4.6.6
  google_fonts: ^6.1.0
  dio: ^5.4.0
  url_launcher: ^6.0.10
  flutter_phone_direct_caller: ^2.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  change_app_package_name: ^1.1.0


flutter: 
  uses-material-design: true

  assets:
  - assets/images/